spring:
  application:
    name: spring-boot-starter
  profiles:
    active: qa

# Default configuration (used when no specific profile is active)
welcome:
  message: Hello Dev Team

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dbcapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Hello Dev Team

---
# QA profile
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/dbcapp_qa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
welcome:
  message: Hello QA Team

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/dbcapp_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Hello PROD Team
